### ISSUE TITLE
ошибка 113 - Invalid user

### ISSUE THREAD

**Issue by jolyk-bugs** [sashafromlibertalia/SchoolBot#3]
ошибка в консоли №113 при использовании команды кика
![image](https://user-images.githubusercontent.com/56132768/124197850-1b417d80-dad8-11eb-88b8-157a70aa2fa9.png)

**Comment by sashafromlibertalia** [comment]
Можно на код взглянуть? И то, как используется сама команда

**Comment by jolyk-bugs** [comment]
Код есть в файле kicker.js 
Команда используется при условии строковой ссылки

**Comment by sashafromlibertalia** [comment]
Это странно, потому что у меня все работает. Такая ошибка возникает на стороне ВК, потому что, возможно, строковая ссылка неверная и API вконтакте не может найти этого пользователя. Проверьте еще раз, пожалуйста 
![Снимок экрана 2021-07-05 в 00 56 33](https://user-images.githubusercontent.com/36822207/124400526-d9107a00-dd2b-11eb-84d9-9da4b0fc22fb.png)

**Comment by jolyk-bugs** [comment]
Ситуация повторяется, может быть попробовать чтобы бот исключал через реплай и, выводил ошибку в сообщении

**Comment by sashafromlibertalia** [comment]
Пробуйте, код у вас на руках. Но я настаиваю, чтобы вы показали, как вы обращаетесь к боту, какие у него права в беседе (только в статусе администратора можно кого-то кикать) и сам код (если вы его меняли)

**Comment by jolyk-bugs** [comment]
Всё решилось, помогло «переустановка бота», но есть еще вопрос: Как правильно должна использоваться команда «/trollgen»?
у меня после отправки сообщения с текстом: «Citgen одобрен, ща будет ржака», бот ничего не присылает

**Comment by sashafromlibertalia** [comment]
Если троллгените сообщение самого бота, то он ничего присылать не будет - ограничение ВКонтакте. А если троллгените человека, то скиньте, пожалуйста, ошибку из консоли

**Comment by jolyk-bugs** [comment]
![image](https://user-images.githubusercontent.com/56132768/128611921-ffa033cc-e2bb-4256-9cbf-e5205c6433e1.png)

**Comment by sashafromlibertalia** [comment]
Действительно баг, пофиксил, проверьте :)

**Comment by jolyk-bugs** [comment]
![image](https://user-images.githubusercontent.com/56132768/128748562-005047d1-9318-4138-8257-cbde081bda13.png)

**Comment by jolyk-bugs** [comment]
исходя из вывода консоли нужно создать папку images с созданным файлом ava.png, а как он выглядит?

**Comment by sashafromlibertalia** [comment]
Добавил обновление бота, сейчас все должно быть хорошо.

**Comment by jolyk-bugs** [comment]
проблема осталась :(
![image](https://user-images.githubusercontent.com/56132768/131248155-19897e24-4ed7-4626-800f-508dcc04d90b.png)

**Comment by jolyk-bugs** [comment]
если у вас работает, покажите, пожалуйста

**Comment by sashafromlibertalia** [comment]
В README.md есть ссылка на бота, которым я сам пользуюсь. Я сейчас просто не дома :( Вообще странно, что такая ошибка появляется, ибо эта картинка сохраняет аватарку пользователя, которую впоследствии вставляет в цитген. Вы скачали свежую версию бота?

**Comment by jolyk-bugs** [comment]
да, установлена свежая версия. пересылаю в лс бота/беседе где есть бот, отвечает: «Citgen одобрен, ща будет ржака», а в консоли ошибка :(
а ваш бот закрыт для приглашения в беседы :(

**Comment by sashafromlibertalia** [comment]
Решение следующее:

1. Создать папку `images`, ибо Git не позволяет залить пустые папки
2. Проверить, что путь до картинки выглядит примерно так:
``` 
/your-folder/SchoolBot/images/ava.png
```

Сейчас беда была в том, что путь выглядел так: 
> /your-folder/SchoolBot/**src**/images/ava.png
